# Generated by Django 5.2 on 2025-04-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Alive', 'Vivo'), ('Dead', 'Muerto'), ('unknown', 'Desconocido')], max_length=50)),
                ('especies', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(choices=[('Female', 'Mujer'), ('Male', 'Hombre'), ('Genderless', 'Sin género'), ('unknown', 'Desconocido')], max_length=50)),
                ('origen', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', models.URLField(blank=True, null=True)),
                ('imagen', models.URLField()),
                ('episodio', models.JSONField(blank=True, default=list)),
                ('URL', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
