# Generated by Django 5.2 on 2025-04-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajes',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
