# Generated by Django 5.2 on 2025-04-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0002_alter_personajes_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personajes',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
