# Generated by Django 5.2 on 2025-04-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0003_alter_personajes_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personajes',
            name='tipo',
        ),
    ]
