# Generated by Django 5.2 on 2025-04-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0004_remove_personajes_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personajes',
            name='episodio',
        ),
    ]
