# Generated by Django 5.2 on 2025-05-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0005_remove_personajes_episodio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personajes',
            options={'ordering': ['-created'], 'verbose_name': 'Personaje', 'verbose_name_plural': 'Personajes'},
        ),
        migrations.AlterField(
            model_name='personajes',
            name='URL',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='especies',
            field=models.CharField(max_length=100, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='estado',
            field=models.CharField(choices=[('Alive', 'Vivo'), ('Dead', 'Muerto'), ('unknown', 'Desconocido')], max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='genero',
            field=models.CharField(choices=[('Female', 'Mujer'), ('Male', 'Hombre'), ('Genderless', 'Sin género'), ('unknown', 'Desconocido')], max_length=50, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='imagen',
            field=models.URLField(verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='origen',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='personajes',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterModelTable(
            name='personajes',
            table='Rick y Morty',
        ),
    ]
